
server:
  port: 28761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-node02
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:18761/eureka/